version: "2"
services:
  samils:
    build: .
    volumes:
      - .:.
    links:
      - mysql
      - postgres
    command: bash
    environment:
      - SAMILS_DB_ADAPTER_MYSQL_HOST=mysql
      - SAMILS_DB_ADAPTER_POSTGRES_HOST=postgres
  mysql:
      image: mysql:5.6
      environment:
        - MYSQL_DATABASE=samils
        - MYSQL_ROOT_PASSWORD=root
      ports:
        - 3306:3306

  postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_DB=samils
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
